Repository AY2324S1-CS2103T-W12-4/tp, pull requests merged in 2023-10, with the labels that each got.

#19 Add User Guide features for Add and List command
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium

#24 Update README.md
  README.md
  docs/images/Ui.png
Labels: tpe.Task

#27 Website title changes and update project links
  README.md
  docs/_config.yml
  docs/index.md
Labels: type.Bug, priority.High

#38 Update user stories in DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: tpe.Task, priority.High

#45 Add Free Time feature to model
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/FreeTime.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedFreeTime.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#57 Fix bugs with MealBuddyCommand
  bin/main/seedu/address/MainApp.class
  bin/main/seedu/address/logic/LogicManager.class
  bin/main/seedu/address/logic/commands/MealBuddyCommand.class
  bin/main/seedu/address/logic/commands/edit/EditCommand.class
  bin/main/seedu/address/logic/commands/edit/EditPersonDescriptor.class
  bin/main/seedu/address/logic/commands/edit/EditUserCommand.class
  bin/main/seedu/address/logic/parser/AddCommandParser.class
  bin/main/seedu/address/logic/parser/AddressBookParser.class
  bin/main/seedu/address/logic/parser/EditCommandParser.class
  bin/main/seedu/address/logic/parser/EditUserCommandParser.class
  bin/main/seedu/address/logic/parser/ParserUtil.class
  bin/main/seedu/address/model/Model.class
  bin/main/seedu/address/model/ModelManager.class
  bin/main/seedu/address/model/person/FreeTime.class
  bin/main/seedu/address/model/person/Person.class
  bin/main/seedu/address/model/user/ReadOnlyUserData.class
  bin/main/seedu/address/model/user/ReadOnlyUserPrefs.class
  bin/main/seedu/address/model/user/UserData.class
  bin/main/seedu/address/model/user/UserPrefs.class
  bin/main/seedu/address/model/util/SampleDataUtil.class
  bin/main/seedu/address/storage/JsonAdaptedFreeTime.class
  bin/main/seedu/address/storage/JsonAdaptedPerson.class
  bin/main/seedu/address/storage/JsonSerializableUserData.class
  bin/main/seedu/address/storage/JsonUserDataStorage.class
  bin/main/seedu/address/storage/JsonUserPrefsStorage.class
  bin/main/seedu/address/storage/Storage.class
  bin/main/seedu/address/storage/StorageManager.class
  bin/main/seedu/address/storage/UserDataStorage.class
  bin/main/seedu/address/storage/UserPrefsStorage.class
  bin/test/seedu/address/logic/LogicManagerTest$1.class
  bin/test/seedu/address/logic/LogicManagerTest.class
  bin/test/seedu/address/logic/commands/AddCommandIntegrationTest.class
  bin/test/seedu/address/logic/commands/AddCommandTest$ModelStub.class
  bin/test/seedu/address/logic/commands/ClearCommandTest.class
  bin/test/seedu/address/logic/commands/CommandTestUtil.class
  bin/test/seedu/address/logic/commands/DeleteCommandTest.class
  bin/test/seedu/address/logic/commands/EditCommandTest.class
  bin/test/seedu/address/logic/commands/EditPersonDescriptorTest.class
  bin/test/seedu/address/logic/commands/FindCommandTest.class
  bin/test/seedu/address/logic/commands/ListCommandTest.class
  bin/test/seedu/address/logic/commands/MealBuddyCommandTest.class
  bin/test/seedu/address/logic/parser/AddressBookParserTest.class
  bin/test/seedu/address/logic/parser/EditCommandParserTest.class
  bin/test/seedu/address/logic/parser/MealBuddyCommandParserTest.class
  bin/test/seedu/address/model/ModelManagerTest.class
  bin/test/seedu/address/model/UserPrefsTest.class
  bin/test/seedu/address/storage/JsonAdaptedPersonTest.class
  bin/test/seedu/address/storage/JsonUserPrefsStorageTest.class
  bin/test/seedu/address/storage/StorageManagerTest.class
  bin/test/seedu/address/testutil/EditPersonDescriptorBuilder.class
  bin/test/seedu/address/testutil/PersonBuilder.class
  bin/test/seedu/address/testutil/PersonUtil.class
  src/main/java/seedu/address/logic/commands/MealBuddyCommand.java
Labels: bug, severity.High

#61 Add half-hour block representation for FreeTime
  src/main/java/seedu/address/logic/commands/edit/EditCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditPersonDescriptor.java
  src/main/java/seedu/address/logic/commands/edit/EditUserCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/FreeTime.java
  src/main/java/seedu/address/model/person/FreeTime/FreeTime.java
  src/main/java/seedu/address/model/person/FreeTime/HalfHourBlocks.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedFreeTime.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task, priority.High

#64 Fix storage bug
  bin/main/seedu/address/MainApp.class
  bin/main/seedu/address/logic/commands/edit/EditPersonDescriptor.class
  bin/main/seedu/address/logic/commands/edit/EditUserCommand.class
  bin/main/seedu/address/model/util/SampleDataUtil.class
  bin/main/seedu/address/storage/JsonAdaptedFreeTime.class
  bin/main/seedu/address/storage/JsonSerializableUserData.class
  bin/test/view/UiPartTest/invalidFile.fxml
  bin/test/view/UiPartTest/validFile.fxml
  bin/test/view/UiPartTest/validFileWithFxRoot.fxml
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedFreeTime.java
  src/main/java/seedu/address/storage/JsonSerializableUserData.java
Labels: bug, severity.High

#65 Bug fix for JsonAdaptedFreeTime
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedFreeTime.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
Labels: type.Bug, severity.High

#66 Update FreeTime constructor to capitalize day name
  src/main/java/seedu/address/model/person/FreeTime/FreeTime.java
Labels: type.Enhancement, priority.Medium

#67 Improved EditUserCommand
  bin/main/seedu/address/logic/commands/MealBuddyCommand.class
  bin/main/seedu/address/logic/commands/edit/EditCommand.class
  bin/main/seedu/address/logic/commands/edit/EditPersonDescriptor.class
  bin/main/seedu/address/logic/commands/edit/EditUserCommand.class
  bin/main/seedu/address/logic/parser/AddCommandParser.class
  bin/main/seedu/address/logic/parser/EditUserCommandParser.class
  bin/main/seedu/address/logic/parser/ParserUtil.class
  bin/main/seedu/address/model/person/FreeTime.class
  bin/main/seedu/address/model/person/FreeTime/FreeTime.class
  bin/main/seedu/address/model/person/FreeTime/HalfHourBlocks.class
  bin/main/seedu/address/model/person/Person.class
  bin/main/seedu/address/model/util/SampleDataUtil.class
  bin/main/seedu/address/storage/JsonAdaptedFreeTime.class
  bin/main/seedu/address/storage/JsonAdaptedPerson.class
  bin/test/seedu/address/logic/commands/CommandTestUtil.class
  bin/test/seedu/address/storage/JsonAdaptedPersonTest.class
  bin/test/seedu/address/testutil/EditPersonDescriptorBuilder.class
  bin/test/seedu/address/testutil/PersonBuilder.class
  bin/test/seedu/address/testutil/PersonUtil.class
  src/main/java/seedu/address/logic/parser/EditUserCommandParser.java
Labels: enhancement

#78 Add user display
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UserCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Task, priority.High

#76 Added test cases for commons directory and AppParameters file
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/test/java/seedu/address/AppParametersTest.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/commons/core/GuiSettingsTest.java
  src/test/java/seedu/address/commons/core/LogsCenterTest.java
  src/test/java/seedu/address/commons/core/VersionTest.java
  src/test/java/seedu/address/commons/util/ToStringBuilderTest.java
Labels: enhancement

#81 Fix bug in EditPersonDescriptor and refactor 'edit' and 'FreeTime' packages
  src/main/java/seedu/address/logic/commands/CommonFreetimeCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditPersonDescriptor.java
  src/main/java/seedu/address/logic/commands/edit/EditUserCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/timetable/FreeTime.java
  src/main/java/seedu/address/model/person/timetable/HalfHourBlocks.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedFreeTime.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommonFreetimeCommandTest.java
  src/test/java/seedu/address/logic/commands/edit/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/edit/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/edit/EditUserCommandTest.java
  src/test/java/seedu/address/logic/parser/CommonFreetimeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MealBuddyCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: bug

#82 Diagram Update for v1.2
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
Labels: type.Task, priority.High

#83 Fix bugs to pass existing testcases
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/user/UserData.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: bug

#85 Improve Checkstyle
  bin/main/seedu/address/MainApp.class
  bin/main/seedu/address/commons/core/LogsCenter.class
  bin/main/seedu/address/logic/LogicManager.class
  bin/main/seedu/address/logic/commands/CommonFreetimeCommand.class
  bin/main/seedu/address/logic/parser/AddCommandParser.class
  bin/main/seedu/address/logic/parser/EditCommandParser.class
  bin/main/seedu/address/model/person/Person.class
  bin/main/seedu/address/model/user/UserData.class
  bin/test/seedu/address/logic/LogicManagerTest.class
  bin/test/seedu/address/logic/commands/CommandTestUtil.class
  bin/test/seedu/address/logic/parser/AddCommandParserTest.class
  bin/test/seedu/address/model/person/PersonTest.class
  bin/test/seedu/address/testutil/EditPersonDescriptorBuilder.class
  bin/test/seedu/address/testutil/PersonUtil.class
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommonFreetimeCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
Labels: help wanted

#86 Improve style for Storage
  bin/main/seedu/address/model/ModelManager.class
  bin/main/seedu/address/model/person/Person.class
  bin/main/seedu/address/model/person/UniquePersonList.class
  bin/main/seedu/address/model/util/SampleDataUtil.class
  bin/main/seedu/address/storage/JsonAdaptedFreeTime.class
  bin/main/seedu/address/storage/JsonSerializableUserData.class
  bin/main/seedu/address/storage/StorageManager.class
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/user/ReadOnlyUserData.java
  src/main/java/seedu/address/model/user/UserData.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedFreeTime.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableUserData.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
Labels: help wanted

#89 Add test cases for new edit classes and improve coding style
  src/main/java/seedu/address/logic/commands/edit/EditPersonDescriptor.java
  src/main/java/seedu/address/logic/commands/edit/EditUserCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditUserCommandParser.java
  src/test/java/seedu/address/AppParametersTest.java
  src/test/java/seedu/address/commons/core/LogsCenterTest.java
  src/test/java/seedu/address/commons/util/ToStringBuilderTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CommonFreetimeCommandTest.java
  src/test/java/seedu/address/logic/commands/edit/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/edit/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/edit/EditUserCommandTest.java
  src/test/java/seedu/address/logic/parser/CommonFreetimeCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#87 Checkstyle corrections
  src/main/java/seedu/address/model/person/timetable/FreeTime.java
  src/main/java/seedu/address/storage/JsonAdaptedFreeTime.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/UserCard.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Bug, priority.Medium

#91 Add Command FreeTime multiplicity resolved
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/timetable/HalfHourBlocks.java
Labels: type.Bug, severity.High

#109 Fix issues with checkstyle and bug in CommonFreeTimeCommand
  bin/test/seedu/address/logic/parser/EditUserCommandParserTest.class
  bin/test/seedu/address/model/person/timetable/FreeTimeTest.class
  bin/test/seedu/address/model/person/timetable/HalfHourBlocksTest.class
  bin/test/seedu/address/model/user/UserDataTest.class
  bin/test/seedu/address/model/user/UserPrefsTest.class
  bin/test/seedu/address/model/util/SampleDataUtilTest.class
  bin/test/seedu/address/storage/JsonAdaptedFreeTimeTest.class
  bin/test/seedu/address/storage/JsonSerializableUserDataTest.class
  settings.gradle
Labels: bug, severity.High

#112 Add test cases for classes under storage package
  src/main/java/seedu/address/logic/commands/CommonFreetimeCommand.java
  src/test/data/JsonUserDataStorageTest/EmptyUserData.json
  src/test/data/JsonUserDataStorageTest/ExtraValuesUserData.json
  src/test/data/JsonUserDataStorageTest/InvalidUserData.json
  src/test/data/JsonUserDataStorageTest/NotJsonFormatUserData.json
  src/test/data/JsonUserDataStorageTest/TypicalUserData.json
  src/test/java/seedu/address/logic/commands/CommonFreetimeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CommonFreetimeCommandParserTest.java
  src/test/java/seedu/address/storage/JsonSerializableUserDataTest.java
  src/test/java/seedu/address/storage/JsonUserDataStorageTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.High

#116 Add new classes for event scheduling and management
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/timetable/BirthdayEvent.java
  src/main/java/seedu/address/model/person/timetable/DatedEvent.java
  src/main/java/seedu/address/model/person/timetable/MeetUpEvent.java
  src/main/java/seedu/address/model/person/timetable/Module.java
  src/main/java/seedu/address/model/person/timetable/TimeBlock.java
  src/main/java/seedu/address/model/person/timetable/WeeklyEvent.java
  src/main/java/seedu/address/model/person/timetable/WeeklySchedule.java
Labels: type.Task, priority.High

#120 Update user stories in Developer Guide
  docs/DeveloperGuide.md
Labels: documentation

#119 Implement Comparable for DatedEvent
  src/main/java/seedu/address/model/person/timetable/DatedEvent.java
  src/main/java/seedu/address/model/person/timetable/HalfHourBlocks.java
  src/main/java/seedu/address/model/person/timetable/TimeBlock.java
Labels: type.Task, priority.High

#124 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#123 Update UserGuide.md with CFT command
  docs/UserGuide.md
Labels: type.Task, priority.High

#125 Updated DG for Storage
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
Labels: documentation, priority.High

#128 Release v1.2.1
  bin/main/seedu/address/MainApp.class
  build.gradle
  src/main/java/seedu/address/MainApp.java
Labels: type.Task, type.Bug, priority.High, severity.VeryLow

#130 Add birthday field to Person and User
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditPersonDescriptor.java
  src/main/java/seedu/address/logic/commands/edit/EditUserCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditUserCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Birthday.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/user/User.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedUser.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/UserCard.java
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/UserCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonUserDataStorageTest/ExtraValuesUserData.json
  src/test/data/JsonUserDataStorageTest/InvalidUserData.json
  src/test/data/JsonUserDataStorageTest/TypicalUserData.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/edit/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/BirthdayTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/user/UserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedUserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditUserDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalUsers.java
  src/test/java/seedu/address/testutil/UserBuilder.java
Labels: priority.High

#131 Add logic to set and remove reminder for event
  src/main/java/seedu/address/logic/commands/RemoveReminderCommand.java
  src/main/java/seedu/address/logic/commands/SetReminderCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RemoveReminderCommandParser.java
  src/main/java/seedu/address/logic/parser/SetReminderCommandParser.java
  src/main/java/seedu/address/model/person/timetable/DatedEvent.java
  src/main/java/seedu/address/model/user/User.java
  src/test/java/seedu/address/logic/commands/RemoveReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/SetReminderCommandTest.java
  src/test/java/seedu/address/logic/parser/RemoveReminderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SetReminderCommandParserTest.java
Labels: priority.High

#132 Restructure Timetable Package
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/timetable/BirthdayEvent.java
  src/main/java/seedu/address/model/person/timetable/Cca.java
  src/main/java/seedu/address/model/person/timetable/DatedEvent.java
  src/main/java/seedu/address/model/person/timetable/HalfHourBlocks.java
  src/main/java/seedu/address/model/person/timetable/MeetUpEvent.java
  src/main/java/seedu/address/model/person/timetable/Module.java
  src/main/java/seedu/address/model/person/timetable/Schedule.java
  src/main/java/seedu/address/model/person/timetable/TimeBlock.java
  src/main/java/seedu/address/model/person/timetable/WeeklyEvent.java
  src/main/java/seedu/address/model/person/timetable/WeeklySchedule.java
  src/main/java/seedu/address/storage/JsonAdaptedDatedEvent.java
Labels: type.Task, priority.High

#135 Fix bug in reminder command
  src/main/java/seedu/address/logic/commands/RemoveReminderCommand.java
  src/main/java/seedu/address/logic/commands/SetReminderCommand.java
  src/main/java/seedu/address/model/person/timetable/DatedEvent.java
  src/main/java/seedu/address/model/user/User.java
Labels: bug

#136 Update storage for schedule
  bin/main/seedu/address/model/person/timetable/Cca.class
  bin/main/seedu/address/model/person/timetable/Module.class
  bin/main/seedu/address/model/person/timetable/Schedule.class
  bin/main/seedu/address/model/person/timetable/TimeBlock.class
  bin/main/seedu/address/storage/JsonAdaptedDatedEvent.class
  bin/main/seedu/address/storage/JsonAdaptedPerson.class
  bin/main/seedu/address/storage/JsonAdaptedUser.class
  bin/main/seedu/address/storage/timetable/JsonAdaptedCca.class
  bin/main/seedu/address/storage/timetable/JsonAdaptedDatedEvent.class
  bin/main/seedu/address/storage/timetable/JsonAdaptedModule.class
  bin/main/seedu/address/storage/timetable/JsonAdaptedSchedule.class
  bin/main/seedu/address/storage/timetable/JsonAdaptedTimeBlock.class
  bin/test/seedu/address/storage/JsonAdaptedPersonTest.class
  src/main/java/seedu/address/model/person/timetable/Cca.java
  src/main/java/seedu/address/model/person/timetable/Module.java
  src/main/java/seedu/address/model/person/timetable/Schedule.java
  src/main/java/seedu/address/model/person/timetable/TimeBlock.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedUser.java
  src/main/java/seedu/address/storage/timetable/JsonAdaptedCca.java
  src/main/java/seedu/address/storage/timetable/JsonAdaptedDatedEvent.java
  src/main/java/seedu/address/storage/timetable/JsonAdaptedModule.java
  src/main/java/seedu/address/storage/timetable/JsonAdaptedSchedule.java
  src/main/java/seedu/address/storage/timetable/JsonAdaptedTimeBlock.java
Labels: type.Task, priority.High

#137 Separate Meet Up and Dated Events in Schedule.java
  src/main/java/seedu/address/model/person/timetable/Schedule.java
Labels: type.Task, priority.High

#138 Add MeetUpEvent to storage
  bin/main/seedu/address/logic/commands/RemoveReminderCommand.class
  bin/main/seedu/address/logic/commands/SetReminderCommand.class
  bin/main/seedu/address/model/person/timetable/DatedEvent.class
  bin/main/seedu/address/model/person/timetable/MeetUpEvent.class
  bin/main/seedu/address/model/person/timetable/Schedule.class
  bin/main/seedu/address/model/user/User.class
  bin/main/seedu/address/storage/JsonAdaptedPerson.class
  bin/main/seedu/address/storage/JsonAdaptedTag.class
  bin/main/seedu/address/storage/JsonAdaptedUser.class
  bin/main/seedu/address/storage/JsonSerializableAddressBook.class
  bin/main/seedu/address/storage/JsonSerializableUserData.class
  bin/main/seedu/address/storage/timetable/JsonAdaptedDatedEvent.class
  bin/main/seedu/address/storage/timetable/JsonAdaptedMeetUpEvent.class
  bin/main/seedu/address/storage/timetable/JsonAdaptedSchedule.class
  src/main/java/seedu/address/model/person/timetable/DatedEvent.java
  src/main/java/seedu/address/model/person/timetable/MeetUpEvent.java
  src/main/java/seedu/address/model/user/User.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonAdaptedUser.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/JsonSerializableUserData.java
  src/main/java/seedu/address/storage/timetable/JsonAdaptedDatedEvent.java
  src/main/java/seedu/address/storage/timetable/JsonAdaptedMeetUpEvent.java
  src/main/java/seedu/address/storage/timetable/JsonAdaptedSchedule.java
Labels: type.Task, priority.High

#140 fix CommonFreeTime, Add, and Edit command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/CommonFreetimeCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditPersonDescriptor.java
  src/main/java/seedu/address/logic/commands/edit/EditUserCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditUserCommandParser.java
  src/main/java/seedu/address/model/person/timetable/Schedule.java
  src/test/java/seedu/address/logic/commands/edit/EditPersonDescriptorTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: bug, severity.High

#141 Add reminder popup for birthdays and events
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/timetable/DatedEvent.java
  src/main/java/seedu/address/model/user/User.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/Reminder.java
Labels: priority.High

#142 Fix Storage Bugs and Add schedule to SampleDataUtil
  bin/main/seedu/address/logic/commands/AddCommand.class
  bin/main/seedu/address/logic/commands/CommandResult.class
  bin/main/seedu/address/logic/commands/CommonFreetimeCommand.class
  bin/main/seedu/address/logic/commands/ExitCommand.class
  bin/main/seedu/address/logic/commands/HelpCommand.class
  bin/main/seedu/address/logic/commands/edit/EditCommand.class
  bin/main/seedu/address/logic/commands/edit/EditPersonDescriptor.class
  bin/main/seedu/address/logic/commands/edit/EditUserCommand.class
  bin/main/seedu/address/logic/parser/AddCommandParser.class
  bin/main/seedu/address/logic/parser/CliSyntax.class
  bin/main/seedu/address/logic/parser/EditCommandParser.class
  bin/main/seedu/address/logic/parser/EditUserCommandParser.class
  bin/main/seedu/address/model/person/timetable/Schedule.class
  bin/main/seedu/address/model/util/SampleDataUtil.class
  bin/main/seedu/address/storage/timetable/JsonAdaptedCca.class
  bin/main/seedu/address/storage/timetable/JsonAdaptedDatedEvent.class
  bin/main/seedu/address/storage/timetable/JsonAdaptedMeetUpEvent.class
  bin/main/seedu/address/storage/timetable/JsonAdaptedModule.class
  bin/main/seedu/address/storage/timetable/JsonAdaptedTimeBlock.class
  bin/test/seedu/address/logic/LogicManagerTest$1.class
  bin/test/seedu/address/logic/LogicManagerTest.class
  bin/test/seedu/address/logic/commands/CommandResultTest.class
  bin/test/seedu/address/logic/commands/CommandTestUtil.class
  bin/test/seedu/address/logic/commands/ExitCommandTest.class
  bin/test/seedu/address/logic/commands/HelpCommandTest.class
  bin/test/seedu/address/logic/commands/edit/EditPersonDescriptorTest.class
  bin/test/seedu/address/logic/parser/AddCommandParserTest.class
  bin/test/seedu/address/logic/parser/EditCommandParserTest.class
  bin/test/seedu/address/logic/parser/EditUserCommandParserTest.class
  bin/test/seedu/address/model/person/PersonTest.class
  bin/test/seedu/address/storage/JsonAdaptedPersonTest.class
  bin/test/seedu/address/testutil/EditPersonDescriptorBuilder.class
  bin/test/seedu/address/testutil/EditUserDescriptorBuilder.class
  bin/test/seedu/address/testutil/PersonBuilder.class
  bin/test/seedu/address/testutil/PersonUtil.class
  bin/test/seedu/address/testutil/TypicalPersons.class
  src/main/java/seedu/address/logic/commands/CommonFreetimeCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditPersonDescriptor.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/timetable/JsonAdaptedCca.java
  src/main/java/seedu/address/storage/timetable/JsonAdaptedDatedEvent.java
  src/main/java/seedu/address/storage/timetable/JsonAdaptedMeetUpEvent.java
  src/main/java/seedu/address/storage/timetable/JsonAdaptedModule.java
  src/main/java/seedu/address/storage/timetable/JsonAdaptedTimeBlock.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: bug, type.Task, type.Bug, priority.High, severity.Medium

#144 Create daily schedule method for Schedule
  src/main/java/seedu/address/model/person/timetable/DatedEvent.java
  src/main/java/seedu/address/model/person/timetable/Schedule.java
Labels: type.Task, priority.High

#145 Fix testutil Classes
  bin/test/seedu/address/logic/commands/CommandTestUtil.class
  bin/test/seedu/address/logic/commands/edit/EditPersonDescriptorTest.class
  bin/test/seedu/address/logic/parser/EditCommandParserTest.class
  bin/test/seedu/address/logic/parser/EditUserCommandParserTest.class
  bin/test/seedu/address/model/person/PersonTest.class
  bin/test/seedu/address/storage/JsonAdaptedPersonTest.class
  bin/test/seedu/address/testutil/EditPersonDescriptorBuilder.class
  bin/test/seedu/address/testutil/EditUserDescriptorBuilder.class
  bin/test/seedu/address/testutil/PersonBuilder.class
  bin/test/seedu/address/testutil/PersonUtil.class
  bin/test/seedu/address/testutil/TypicalPersons.class
  bin/test/seedu/address/testutil/TypicalUsers.class
  bin/test/seedu/address/testutil/UserBuilder.class
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditUserDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalUsers.java
  src/test/java/seedu/address/testutil/UserBuilder.java
Labels: bug, type.Task, type.Bug, severity.Low

#143 fix CommonFreeTime, Add, Edit command
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/CommonFreetimeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteEventCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/timetable/Schedule.java
Labels: type.Task, priority.High

#146 Remove freetime from test cases
  src/main/java/seedu/address/model/person/timetable/DatedEvent.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/edit/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditUserCommandParserTest.java
Labels: bug

#149 Fix bug in SampleDataUtil
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
Labels: bug

#152 Change testutil and add new testcases
  src/main/java/seedu/address/logic/commands/RemoveReminderCommand.java
  src/main/java/seedu/address/logic/commands/SetReminderCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditPersonDescriptor.java
  src/main/java/seedu/address/logic/commands/edit/EditUserDescriptor.java
  src/main/java/seedu/address/logic/parser/RemoveReminderCommandParser.java
  src/main/java/seedu/address/model/person/timetable/Schedule.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CommonFreetimeCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/SetReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/edit/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/edit/EditUserDescriptorTest.java
  src/test/java/seedu/address/logic/parser/RemoveReminderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SetReminderCommandParserTest.java
  src/test/java/seedu/address/testutil/DatedEventsBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditUserDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalDatedEvents.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalSchedule.java
  src/test/java/seedu/address/testutil/TypicalUsers.java
  src/test/java/seedu/address/testutil/UserBuilder.java
Labels: bug, priority.High

#150 Standardise toString methods for timetable package
  src/main/java/seedu/address/model/person/timetable/Cca.java
  src/main/java/seedu/address/model/person/timetable/DatedEvent.java
  src/main/java/seedu/address/model/person/timetable/MeetUpEvent.java
  src/main/java/seedu/address/model/person/timetable/Module.java
  src/main/java/seedu/address/model/person/timetable/Schedule.java
  src/main/java/seedu/address/model/person/timetable/TimeBlock.java
Labels: type.Task, priority.Medium
