Repository AY2324S1-CS2103T-W12-4/tp, pull requests merged in 2023-11, with the labels that each got.

#154 Add Intro to UG
  bin/main/seedu/address/logic/commands/AddEventCommand.class
  bin/main/seedu/address/logic/commands/DeleteEventCommand.class
  bin/main/seedu/address/logic/parser/DeleteEventCommandParser.class
  bin/main/seedu/address/model/person/timetable/TimeBlock.class
  bin/test/seedu/address/logic/LogicManagerTest$1.class
  bin/test/seedu/address/logic/LogicManagerTest.class
  bin/test/seedu/address/logic/commands/AddCommandTest$ModelStub.class
  bin/test/seedu/address/logic/commands/AddCommandTest$ModelStubAcceptingPersonAdded.class
  bin/test/seedu/address/logic/commands/AddCommandTest$ModelStubWithPerson.class
  bin/test/seedu/address/logic/commands/CommandResultTest.class
  bin/test/seedu/address/logic/commands/CommandTestUtil.class
  bin/test/seedu/address/logic/commands/ExitCommandTest.class
  bin/test/seedu/address/logic/commands/HelpCommandTest.class
  bin/test/seedu/address/logic/commands/edit/EditPersonDescriptorTest.class
  bin/test/seedu/address/logic/parser/AddCommandParserTest.class
  bin/test/seedu/address/logic/parser/EditCommandParserTest.class
  bin/test/seedu/address/logic/parser/EditUserCommandParserTest.class
  docs/UserGuide.md
Labels: documentation

#156 Reformat TimeBlock to abstract class
  src/main/java/seedu/address/model/person/timetable/Cca.java
  src/main/java/seedu/address/model/person/timetable/DatedEvent.java
  src/main/java/seedu/address/model/person/timetable/MeetUpEvent.java
  src/main/java/seedu/address/model/person/timetable/Module.java
  src/main/java/seedu/address/model/person/timetable/Schedule.java
  src/main/java/seedu/address/model/person/timetable/TimeBlock.java
  src/main/java/seedu/address/storage/timetable/JsonAdaptedCca.java
Labels: type.Task, priority.High

#155 Fix code length in CommonFreeTimeCommand
  .vscode/settings.json
  src/main/java/seedu/address/logic/commands/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/CommonFreetimeCommand.java
Labels: type.Enhancement, priority.Low

#158 Fix testcases and checkstyleTest
  src/main/java/seedu/address/logic/commands/edit/EditPersonDescriptor.java
  src/main/java/seedu/address/logic/commands/edit/EditUserDescriptor.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditUserCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Birthday.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/timetable/Schedule.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CommonFreetimeCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/SetReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/edit/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/edit/EditUserDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditUserCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveReminderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SetReminderCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/timetable/JsonAdaptedCcaTest.java
  src/test/java/seedu/address/storage/timetable/JsonAdaptedDatedEventTest.java
  src/test/java/seedu/address/storage/timetable/JsonAdaptedMeetUpEventTest.java
  src/test/java/seedu/address/storage/timetable/JsonAdaptedModuleTest.java
  src/test/java/seedu/address/storage/timetable/JsonAdaptedScheduleTest.java
  src/test/java/seedu/address/testutil/DatedEventsBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditUserDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/ScheduleBuilder.java
  src/test/java/seedu/address/testutil/TypicalDatedEvents.java
  src/test/java/seedu/address/testutil/TypicalSchedule.java
  src/test/java/seedu/address/testutil/TypicalUsers.java
  src/test/java/seedu/address/testutil/UserBuilder.java
Labels: bug

#162 Remove 5 methods from SampleDataUtil and fix checkstyle for all classes
  bin/main/view/HelpWindow.css
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/CommonFreetimeCommand.java
  src/main/java/seedu/address/logic/commands/RemoveEventCommand.java
  src/main/java/seedu/address/logic/commands/RemoveReminderCommand.java
  src/main/java/seedu/address/logic/commands/RemoveScheduleCommand.java
  src/main/java/seedu/address/logic/commands/SetReminderCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditUserCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditUserDescriptor.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditUserCommandParser.java
  src/main/java/seedu/address/logic/parser/RemoveScheduleCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/resources/view/HelpWindow.css
Labels: documentation, enhancement, priority.Medium

#164 Add testcases for new classes and newly added codes
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RemoveEventCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddScheduleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveScheduleCommandParserTest.java
  src/test/java/seedu/address/model/person/BirthdayTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: bug, priority.High

#165 Add testcases for JsonAdapted models
  src/main/java/seedu/address/model/user/User.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/user/UserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedFreeTimeTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedUserTest.java
Labels: priority.High

#167 Bug fix for Schedule & HalfHourBlocks
  src/main/java/seedu/address/model/person/timetable/HalfHourBlocks.java
  src/main/java/seedu/address/model/person/timetable/Schedule.java
Labels: type.Bug, severity.High

#168 Update UserGuide
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/CommonFreetimeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CommonFreetimeCommandParser.java
Labels: documentation, priority.Low

#169 Add test cases for models
  src/test/java/seedu/address/model/person/timetable/CcaTest.java
  src/test/java/seedu/address/model/person/timetable/DatedEventTest.java
  src/test/java/seedu/address/model/person/timetable/HalfHourBlocksTest.java
  src/test/java/seedu/address/model/person/timetable/ModuleTest.java
  src/test/java/seedu/address/model/person/timetable/ScheduleTest.java
Labels: priority.High

#170 Edit test cases for CommonFreetimeCommand
  src/test/java/seedu/address/logic/commands/CommonFreetimeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CommonFreetimeCommandParserTest.java
Labels: bug

#171 Fix FreeTime bug
  bin/main/seedu/address/logic/commands/CommonFreetimeCommand.class
  bin/main/seedu/address/logic/parser/AddressBookParser.class
  bin/main/seedu/address/logic/parser/CommonFreetimeCommandParser.class
  bin/main/seedu/address/model/person/timetable/HalfHourBlocks.class
  bin/main/seedu/address/model/person/timetable/Schedule.class
  bin/test/seedu/address/logic/commands/CommonFreetimeCommandTest.class
  bin/test/seedu/address/logic/parser/AddressBookParserTest.class
  bin/test/seedu/address/logic/parser/CommonFreetimeCommandParserTest.class
  src/main/java/seedu/address/model/person/timetable/Schedule.java
Labels: bug, severity.Medium

#172 Fix Ui bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/SelectedFriendCard.java
  src/main/java/seedu/address/ui/UserCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/SelectedFriendCard.fxml
  src/main/resources/view/UserCard.fxml
Labels: bug, documentation

#175 Fix bugs with add/remove event/schedule commands
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/RemoveEventCommand.java
  src/main/java/seedu/address/logic/commands/RemoveScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddScheduleCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: bug, severity.Medium

#176 Add Schedule to TypicalPersons
  bin/main/seedu/address/logic/commands/AddEventCommand.class
  bin/main/seedu/address/logic/commands/AddScheduleCommand.class
  bin/main/seedu/address/logic/commands/CommandResult.class
  bin/main/seedu/address/logic/commands/CommonFreetimeCommand.class
  bin/main/seedu/address/logic/commands/RemoveEventCommand.class
  bin/main/seedu/address/logic/commands/RemoveScheduleCommand.class
  bin/main/seedu/address/logic/parser/AddEventCommandParser.class
  bin/main/seedu/address/logic/parser/AddScheduleCommandParser.class
  bin/main/seedu/address/logic/parser/AddressBookParser.class
  bin/main/seedu/address/logic/parser/RemoveEventCommandParser.class
  bin/main/seedu/address/model/person/timetable/Schedule.class
  bin/main/seedu/address/ui/MainWindow$1.class
  bin/main/seedu/address/ui/MainWindow.class
  bin/main/seedu/address/ui/SelectedFriendCard.class
  bin/main/seedu/address/ui/UserCard.class
  bin/main/view/DarkTheme.css
  bin/main/view/HelpWindow.fxml
  bin/main/view/MainWindow.fxml
  bin/main/view/SelectedFriendCard.fxml
  bin/main/view/UserCard.fxml
  bin/test/seedu/address/logic/commands/AddEventCommandTest.class
  bin/test/seedu/address/logic/commands/CommandResultTest.class
  bin/test/seedu/address/logic/commands/CommonFreetimeCommandTest.class
  bin/test/seedu/address/logic/commands/RemoveEventCommandTest.class
  bin/test/seedu/address/logic/commands/edit/EditCommandTest.class
  bin/test/seedu/address/logic/parser/AddEventCommandParserTest.class
  bin/test/seedu/address/logic/parser/AddScheduleCommandParserTest.class
  bin/test/seedu/address/logic/parser/AddressBookParserTest.class
  bin/test/seedu/address/logic/parser/CommonFreetimeCommandParserTest.class
  bin/test/seedu/address/logic/parser/RemoveEventCommandParserTest.class
  bin/test/seedu/address/logic/parser/RemoveScheduleCommandParserTest.class
  bin/test/seedu/address/model/person/timetable/CcaTest.class
  bin/test/seedu/address/model/person/timetable/DatedEventTest.class
  bin/test/seedu/address/model/person/timetable/HalfHourBlocksTest.class
  bin/test/seedu/address/model/person/timetable/ModuleTest.class
  bin/test/seedu/address/model/person/timetable/ScheduleTest.class
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
Labels: type.Task, priority.Medium

#178 Fix test cases for logic
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/CommonFreetimeCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveEventCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddScheduleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveScheduleCommandParserTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalSchedule.java
Labels: bug

#237 Fix Add and Edit Command
  bin/main/seedu/address/logic/commands/AddCommand.class
  bin/main/seedu/address/logic/commands/AddEventCommand.class
  bin/main/seedu/address/logic/commands/AddScheduleCommand.class
  bin/main/seedu/address/logic/commands/RemoveEventCommand.class
  bin/main/seedu/address/logic/commands/RemoveScheduleCommand.class
  bin/main/seedu/address/logic/parser/AddCommandParser.class
  bin/main/seedu/address/logic/parser/AddEventCommandParser.class
  bin/main/seedu/address/logic/parser/AddScheduleCommandParser.class
  bin/main/seedu/address/logic/parser/ParserUtil.class
  bin/main/seedu/address/logic/parser/RemoveEventCommandParser.class
  bin/main/seedu/address/logic/parser/RemoveScheduleCommandParser.class
  bin/main/seedu/address/model/AddressBook.class
  bin/main/seedu/address/model/Model.class
  bin/main/seedu/address/model/ModelManager.class
  bin/main/seedu/address/model/person/Address.class
  bin/main/seedu/address/model/person/Birthday.class
  bin/main/seedu/address/model/person/Email.class
  bin/main/seedu/address/model/person/Name.class
  bin/main/seedu/address/model/person/Person.class
  bin/main/seedu/address/model/person/Phone.class
  bin/main/seedu/address/model/person/UniquePersonList.class
  bin/main/seedu/address/model/person/timetable/MeetUpEvent.class
  bin/main/seedu/address/storage/JsonAdaptedPerson.class
  bin/main/seedu/address/storage/JsonAdaptedUser.class
  bin/test/seedu/address/logic/commands/AddCommandTest$ModelStub.class
  bin/test/seedu/address/logic/commands/AddCommandTest$ModelStubAcceptingPersonAdded.class
  bin/test/seedu/address/logic/commands/AddCommandTest$ModelStubWithPerson.class
  bin/test/seedu/address/logic/commands/AddEventCommandTest.class
  bin/test/seedu/address/logic/commands/AddScheduleCommandTest.class
  bin/test/seedu/address/logic/commands/CommonFreetimeCommandTest.class
  bin/test/seedu/address/logic/commands/RemoveEventCommandTest.class
  bin/test/seedu/address/logic/commands/RemoveScheduleCommandTest.class
  bin/test/seedu/address/logic/parser/AddCommandParserTest.class
  bin/test/seedu/address/logic/parser/AddEventCommandParserTest.class
  bin/test/seedu/address/logic/parser/AddScheduleCommandParserTest.class
  bin/test/seedu/address/logic/parser/EditCommandParserTest.class
  bin/test/seedu/address/logic/parser/EditUserCommandParserTest.class
  bin/test/seedu/address/logic/parser/RemoveEventCommandParserTest.class
  bin/test/seedu/address/logic/parser/RemoveScheduleCommandParserTest.class
  bin/test/seedu/address/storage/JsonAdaptedPersonTest.class
  bin/test/seedu/address/storage/JsonAdaptedUserTest.class
  bin/test/seedu/address/storage/JsonSerializableAddressBookTest.class
  bin/test/seedu/address/testutil/TypicalSchedule.class
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Birthday.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: bug, priority.High, severity.Low

#238 Fix bug of reminders for dated events not appearing at launch
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/timetable/Schedule.java
  src/main/java/seedu/address/model/user/User.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/RemoveReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/SetReminderCommandTest.java
  src/test/java/seedu/address/model/user/UserTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalSchedule.java
Labels: bug, documentation

#240 Fix test cases bugs in Model
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/BirthdayTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedUserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: bug

#242 Update Command Summary in UserGuide.md
  docs/UserGuide.md
Labels: type.Bug, severity.Medium

#243 Fix Broken testcases
  bin/main/seedu/address/model/person/Name.class
  bin/main/seedu/address/model/person/timetable/Schedule.class
  bin/main/seedu/address/model/user/User.class
  bin/test/seedu/address/logic/commands/AddCommandTest$ModelStubAcceptingPersonAdded.class
  bin/test/seedu/address/logic/commands/RemoveReminderCommandTest.class
  bin/test/seedu/address/logic/commands/SetReminderCommandTest.class
  bin/test/seedu/address/logic/parser/AddCommandParserTest.class
  bin/test/seedu/address/logic/parser/ParserUtilTest.class
  bin/test/seedu/address/model/person/AddressTest.class
  bin/test/seedu/address/model/person/BirthdayTest.class
  bin/test/seedu/address/model/person/EmailTest.class
  bin/test/seedu/address/model/person/NameContainsKeywordsPredicateTest.class
  bin/test/seedu/address/model/person/NameTest.class
  bin/test/seedu/address/model/person/PersonTest.class
  bin/test/seedu/address/model/person/PhoneTest.class
  bin/test/seedu/address/model/user/UserTest.class
  bin/test/seedu/address/storage/JsonAdaptedPersonTest.class
  bin/test/seedu/address/storage/JsonAdaptedUserTest.class
  bin/test/seedu/address/storage/JsonSerializableAddressBookTest.class
  bin/test/seedu/address/testutil/TypicalPersons.class
  bin/test/seedu/address/testutil/TypicalSchedule.class
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedUserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: bug, severity.Low

#244 Add test cases for new commands and parsers
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/RemoveScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddScheduleCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/timetable/TimeBlock.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/CommonFreetimeCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveEventCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddScheduleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveScheduleCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/timetable/TimeBlockTest.java
Labels: enhancement, priority.High

#245 Update PPP
  docs/team/teozhengyang.md
Labels: documentation

#246 Fix issue with rmschedule command
  src/main/java/seedu/address/logic/commands/RemoveScheduleCommand.java
Labels: bug, severity.High

#248 Rectify Documentation Bugs in UserGuide.md
  docs/UserGuide.md
Labels: type.Bug, severity.High

#249 Changes to the help pop-up
  docs/UserGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: bug, priority.High

#247 Fix bugs in logic classes
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/CommonFreetimeCommand.java
  src/main/java/seedu/address/logic/commands/RemoveEventCommand.java
  src/main/java/seedu/address/logic/commands/RemoveScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/RemoveEventCommandParser.java
  src/main/java/seedu/address/logic/parser/RemoveScheduleCommandParser.java
  src/main/java/seedu/address/model/person/Birthday.java
  src/main/java/seedu/address/model/person/timetable/Schedule.java
  src/test/data/JsonSerializableAddressBookTest/smallTypicalPersonsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommonFreetimeCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddScheduleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveScheduleCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedUserTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: bug

#252 Update lululwtv.md
  docs/UserGuide.md
  docs/team/lululwtv.md
  src/main/java/seedu/address/logic/commands/CommonFreetimeCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/RemoveEventCommandParser.java
  src/main/java/seedu/address/logic/parser/RemoveScheduleCommandParser.java
  src/main/java/seedu/address/model/person/timetable/DatedEvent.java
Labels: bug, documentation, severity.High

#253 Update owenyeo.md
  docs/UserGuide.md
  docs/images/ui-overview.png
  docs/team/owenyeo.md
Labels: bug, documentation

#258 Module code made more flexible
  src/main/java/seedu/address/model/person/timetable/Module.java
Labels: type.Bug, severity.Medium

#259 UserGuide.md restructure
  docs/UserGuide.md
Labels: documentation, type.Enhancement

#260 Bug fix: Exclusive end time for FreeTime
  src/main/java/seedu/address/model/person/timetable/FreeTime.java
  src/main/java/seedu/address/model/person/timetable/Module.java
  src/main/java/seedu/address/model/person/timetable/Schedule.java
  src/main/java/seedu/address/model/person/timetable/TimeBlock.java
Labels: type.Bug, severity.Medium

#261 Fix bugs in test cases for logic classes
  src/test/java/seedu/address/logic/parser/AddEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddScheduleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveScheduleCommandParserTest.java
Labels: bug

#262 Fix bugs in logic classes
  src/main/java/seedu/address/logic/parser/AddScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/RemoveEventCommandParser.java
  src/main/java/seedu/address/logic/parser/RemoveScheduleCommandParser.java
  src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/CommonFreetimeCommandTest.java
  src/test/java/seedu/address/model/person/timetable/ModuleTest.java
  src/test/java/seedu/address/testutil/TypicalSchedule.java
  src/test/java/seedu/address/testutil/TypicalUsers.java
Labels: bug

#265 Fix bugs
  src/main/java/seedu/address/logic/parser/AddScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/RemoveEventCommandParser.java
  src/main/java/seedu/address/logic/parser/RemoveScheduleCommandParser.java
  src/main/java/seedu/address/model/person/timetable/Schedule.java
  src/test/java/seedu/address/logic/commands/CommonFreetimeCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemoveScheduleCommandParserTest.java
  src/test/java/seedu/address/model/person/timetable/ScheduleTest.java
Labels: bug

#266 Fix rmschedule command bug
  docs/team/lululwtv.md
  src/main/java/seedu/address/model/person/timetable/Schedule.java
Labels: bug, severity.High

#267 Bug fix: Wrong error message in CommonFreeTimeCommand
  src/main/java/seedu/address/logic/commands/CommonFreetimeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CommonFreeTimeCommandParser.java
  src/main/java/seedu/address/model/person/timetable/Schedule.java
  src/test/java/seedu/address/logic/commands/CommonFreeTimeCommandTest.java
  src/test/java/seedu/address/logic/parser/CommonFreeTimeCommandParserTest.java
  src/test/java/seedu/address/model/person/timetable/ModuleTest.java
  src/test/java/seedu/address/testutil/TypicalSchedule.java
Labels: type.Bug, severity.Medium

#270 Add more FAQ to UG
  docs/UserGuide.md
Labels: documentation

#272 Fix Add Command
  bin/main/seedu/address/logic/Messages.class
  bin/main/seedu/address/logic/commands/CommonFreetimeCommand.class
  bin/main/seedu/address/logic/parser/AddCommandParser.class
  bin/main/seedu/address/logic/parser/AddScheduleCommandParser.class
  bin/main/seedu/address/logic/parser/AddressBookParser.class
  bin/main/seedu/address/logic/parser/CommonFreetimeCommandParser.class
  bin/main/seedu/address/logic/parser/RemoveEventCommandParser.class
  bin/main/seedu/address/logic/parser/RemoveScheduleCommandParser.class
  bin/main/seedu/address/model/person/timetable/Schedule.class
  bin/test/seedu/address/logic/commands/AddScheduleCommandTest.class
  bin/test/seedu/address/logic/commands/CommonFreetimeCommandTest.class
  bin/test/seedu/address/logic/commands/RemoveScheduleCommandTest.class
  bin/test/seedu/address/logic/parser/AddEventCommandParserTest.class
  bin/test/seedu/address/logic/parser/AddScheduleCommandParserTest.class
  bin/test/seedu/address/logic/parser/AddressBookParserTest.class
  bin/test/seedu/address/logic/parser/CommonFreetimeCommandParserTest.class
  bin/test/seedu/address/logic/parser/RemoveEventCommandParserTest.class
  bin/test/seedu/address/logic/parser/RemoveScheduleCommandParserTest.class
  bin/test/seedu/address/model/person/timetable/ModuleTest.class
  bin/test/seedu/address/model/person/timetable/ScheduleTest.class
  bin/test/seedu/address/testutil/TypicalSchedule.class
  bin/test/seedu/address/testutil/TypicalUsers.class
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
Labels: bug, severity.Medium

#273 Change UG tone
  docs/UserGuide.md
Labels: documentation

#274 Update DeveloperGuide
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/TimetableClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/TimetableClassDiagram.png
Labels: documentation, priority.High

#275 Update DG Storage
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/TimetableStorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
  docs/images/TimetableStorageClassDiagram.png
Labels: documentation

#276 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation, priority.High

#279 Fix discrepancies in error message
  src/main/java/seedu/address/model/person/timetable/Schedule.java
Labels: type.Bug, severity.VeryLow

#278 ReadMe and UG updates
  README.md
  docs/UserGuide.md
  docs/images/Ui-Final.png
Labels: documentation

#280 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/AddScheduleSequenceDiagram.puml
  docs/images/AddScheduleSequenceDiagram.png
  docs/team/lululwtv.md
Labels: documentation

#281 docs updates
  README.md
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/ui-view-friend.png
Labels: documentation

#282 Update UG and Standardised error messages
  docs/UserGuide.md
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/RemoveEventCommand.java
  src/main/java/seedu/address/logic/commands/RemoveScheduleCommand.java
  src/main/java/seedu/address/model/person/timetable/FreeTime.java
  src/main/java/seedu/address/model/person/timetable/Schedule.java
  src/test/java/seedu/address/logic/commands/RemoveScheduleCommandTest.java
Labels: documentation, priority.Medium

#283 Add colours to fenced code blocks in user guide
  docs/UserGuide.md
Labels: documentation

#284 Update DG
  README.md
  docs/DeveloperGuide.md
  docs/diagrams/TimetableStorageClassDiagram.puml
  docs/team/kristayeo.md
  docs/team/owenyeo.md
  docs/team/teozhengyang.md
Labels: documentation

#285 Fix Edit and EditUser
  bin/main/seedu/address/logic/commands/edit/EditCommand.class
  bin/main/seedu/address/logic/commands/edit/EditUserCommand.class
  bin/main/seedu/address/logic/parser/AddCommandParser.class
  bin/main/seedu/address/model/ModelManager.class
  bin/main/seedu/address/model/person/timetable/Schedule.class
  bin/main/seedu/address/model/user/UserData.class
  bin/test/seedu/address/logic/commands/edit/EditCommandTest.class
  bin/test/seedu/address/logic/commands/edit/EditUserCommandTest.class
  bin/test/seedu/address/testutil/EditPersonDescriptorBuilder.class
  bin/test/seedu/address/testutil/EditUserDescriptorBuilder.class
  src/main/java/seedu/address/logic/commands/edit/EditCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditUserCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/user/UserData.java
  src/test/java/seedu/address/logic/commands/edit/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/edit/EditUserCommandTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditUserDescriptorBuilder.java
Labels: bug, severity.Medium

#286 site page update
  docs/index.md
Labels: documentation

#287 Change colours for input/output
  docs/UserGuide.md
Labels: documentation

#288 Add more FAQs to UG
  docs/UserGuide.md
Labels: documentation

#289 DG: product scope
  docs/AboutUs.md
  docs/DeveloperGuide.md
Labels: documentation

#290 Update documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#295 Update UserGuide and DeveloperGuide
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/TimetableProblemDomain.puml
  docs/diagrams/TimetableSolutionDomain.puml
  docs/images/TimetableProblemDomain.png
  docs/images/TimetableSolutionDomain.png
  docs/index.md
Labels: documentation, priority.High

#297 Update DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#298 Change error message for add command
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
Labels: bug, severity.VeryLow

#291 Add EditUser in DG
  bin/main/seedu/address/logic/commands/AddEventCommand.class
  bin/main/seedu/address/logic/commands/AddScheduleCommand.class
  bin/main/seedu/address/logic/commands/RemoveEventCommand.class
  bin/main/seedu/address/logic/commands/RemoveScheduleCommand.class
  bin/main/seedu/address/logic/parser/AddEventCommandParser.class
  bin/main/seedu/address/logic/parser/AddScheduleCommandParser.class
  bin/main/seedu/address/logic/parser/EditUserCommandParser.class
  bin/main/seedu/address/logic/parser/RemoveEventCommandParser.class
  bin/main/seedu/address/model/person/timetable/FreeTime.class
  bin/main/seedu/address/model/person/timetable/Schedule.class
  bin/main/seedu/address/storage/JsonAdaptedTag.class
  bin/main/seedu/address/storage/JsonAdaptedUser.class
  bin/main/seedu/address/storage/JsonAddressBookStorage.class
  bin/main/seedu/address/storage/JsonSerializableAddressBook.class
  bin/main/seedu/address/storage/JsonSerializableUserData.class
  bin/test/seedu/address/logic/commands/RemoveScheduleCommandTest.class
  bin/test/seedu/address/logic/parser/AddEventCommandParserTest.class
  bin/test/seedu/address/logic/parser/AddScheduleCommandParserTest.class
  bin/test/seedu/address/logic/parser/RemoveEventCommandParserTest.class
  docs/DeveloperGuide.md
  docs/diagrams/EditUserExecuteSequenceDiagram.puml
  docs/diagrams/EditUserSequenceDiagram.puml
  docs/images/EditUserExecuteSequenceDiagram.png
  docs/images/EditUserSequenceDiagram.png
  src/main/java/seedu/address/logic/parser/EditUserCommandParser.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonAdaptedUser.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/JsonSerializableUserData.java
Labels: documentation

#300 Update DG
  docs/DeveloperGuide.md
  docs/images/AddScheduleSequenceDiagram.png
Labels: documentation

#302 fix img ref in readme
  README.md
  docs/index.md
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonAdaptedUser.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/JsonSerializableUserData.java
Labels: bug, documentation

#303 Change addschedule sequence diagram
  docs/diagrams/AddScheduleSequenceDiagram.puml
Labels: documentation

#305 Fix AddCommand requiring t/
  bin/main/seedu/address/logic/parser/AddCommandParser.class
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
Labels: bug, severity.Medium

#304 UG edits
  docs/UserGuide.md
Labels: documentation

#306 Fix bug in addCommandParser test cases
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: bug

#310 Update AddScheduleSequenceDiagram.png
  docs/images/AddScheduleSequenceDiagram.png
Labels: documentation

#308 Add reminder functionality to UI section in DG
  docs/DeveloperGuide.md
Labels: documentation

#312 Update AboutUs.md
  docs/AboutUs.md
Labels: documentation

#311 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: documentation

#313 Remove 1 line
  bin/test/seedu/address/logic/parser/AddCommandParserTest.class
  docs/DeveloperGuide.md
Labels: bug, documentation

#314 Edit PPP
  docs/team/teozhengyang.md
Labels: documentation

#316 dg updates
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ClickToViewActivityDiagram.puml
  docs/images/ClickToViewActivityDiagram.png
  docs/images/Reminder-window.png
Labels: documentation

#317 Change header to TimetaBRO
  docs/_sass/minima/_base.scss
Labels: bug

#319 Update PPP
  docs/team/owenyeo.md
Labels: documentation

#320 Update PPP
  docs/team/lululwtv.md
Labels: documentation

#322 Fix PPP wording
  docs/team/owenyeo.md
Labels: bug, documentation

#323 UG: fix link to params
  docs/UserGuide.md
Labels: documentation

#321 PPP and UG update
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/andrefoo.md
Labels: documentation

#325 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation

#327 DG edits
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/images/UiClassDiagram.png
Labels: documentation

#328 Fix ReadMe
  README.md
  bin/main/seedu/address/model/person/timetable/Cca.class
  bin/main/seedu/address/model/person/timetable/DatedEvent.class
  bin/main/seedu/address/model/person/timetable/Module.class
  bin/test/seedu/address/model/person/timetable/CcaTest.class
  bin/test/seedu/address/model/person/timetable/DatedEventTest.class
  bin/test/seedu/address/model/person/timetable/ModuleTest.class
  src/main/java/seedu/address/model/person/timetable/Cca.java
  src/main/java/seedu/address/model/person/timetable/DatedEvent.java
  src/main/java/seedu/address/model/person/timetable/Module.java
  src/test/java/seedu/address/model/person/timetable/CcaTest.java
  src/test/java/seedu/address/model/person/timetable/DatedEventTest.java
  src/test/java/seedu/address/model/person/timetable/ModuleTest.java
Labels: bug, documentation

#329 DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#330 Update PPP
  docs/team/lululwtv.md
Labels: documentation

#332 Update UG
  bin/main/seedu/address/model/person/timetable/DatedEvent.class
  bin/main/seedu/address/model/person/timetable/Schedule.class
  docs/UserGuide.md
Labels: documentation

#333 Fix DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: documentation

#334 Update UG
  docs/UserGuide.md
Labels: documentation

#335 Fix use cases
  docs/DeveloperGuide.md
Labels: documentation

#337 Update UG
  docs/UserGuide.md
  docs/images/HelpPopUp.png
Labels: documentation
